/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppTestingServicesIndexRouteImport } from './routes/_app/testing-services/index'
import { Route as AppOurVenuesIndexRouteImport } from './routes/_app/our-venues/index'
import { Route as AppFeesIndexRouteImport } from './routes/_app/fees/index'
import { Route as AppExamPreparationCoursesIndexRouteImport } from './routes/_app/exam-preparation-courses/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/_dashboard/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestingServicesIndexRoute = AppTestingServicesIndexRouteImport.update({
  id: '/testing-services/',
  path: '/testing-services/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOurVenuesIndexRoute = AppOurVenuesIndexRouteImport.update({
  id: '/our-venues/',
  path: '/our-venues/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeesIndexRoute = AppFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamPreparationCoursesIndexRoute =
  AppExamPreparationCoursesIndexRouteImport.update({
    id: '/exam-preparation-courses/',
    path: '/exam-preparation-courses/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppDashboardIndexRoute
  '/exam-preparation-courses/': typeof AppExamPreparationCoursesIndexRoute
  '/fees/': typeof AppFeesIndexRoute
  '/our-venues/': typeof AppOurVenuesIndexRoute
  '/testing-services/': typeof AppTestingServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppDashboardIndexRoute
  '/exam-preparation-courses': typeof AppExamPreparationCoursesIndexRoute
  '/fees': typeof AppFeesIndexRoute
  '/our-venues': typeof AppOurVenuesIndexRoute
  '/testing-services': typeof AppTestingServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/exam-preparation-courses/': typeof AppExamPreparationCoursesIndexRoute
  '/_app/fees/': typeof AppFeesIndexRoute
  '/_app/our-venues/': typeof AppOurVenuesIndexRoute
  '/_app/testing-services/': typeof AppTestingServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam-preparation-courses/'
    | '/fees/'
    | '/our-venues/'
    | '/testing-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam-preparation-courses'
    | '/fees'
    | '/our-venues'
    | '/testing-services'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_dashboard/'
    | '/_app/exam-preparation-courses/'
    | '/_app/fees/'
    | '/_app/our-venues/'
    | '/_app/testing-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/testing-services/': {
      id: '/_app/testing-services/'
      path: '/testing-services'
      fullPath: '/testing-services/'
      preLoaderRoute: typeof AppTestingServicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/our-venues/': {
      id: '/_app/our-venues/'
      path: '/our-venues'
      fullPath: '/our-venues/'
      preLoaderRoute: typeof AppOurVenuesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fees/': {
      id: '/_app/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof AppFeesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exam-preparation-courses/': {
      id: '/_app/exam-preparation-courses/'
      path: '/exam-preparation-courses'
      fullPath: '/exam-preparation-courses/'
      preLoaderRoute: typeof AppExamPreparationCoursesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppExamPreparationCoursesIndexRoute: typeof AppExamPreparationCoursesIndexRoute
  AppFeesIndexRoute: typeof AppFeesIndexRoute
  AppOurVenuesIndexRoute: typeof AppOurVenuesIndexRoute
  AppTestingServicesIndexRoute: typeof AppTestingServicesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppExamPreparationCoursesIndexRoute: AppExamPreparationCoursesIndexRoute,
  AppFeesIndexRoute: AppFeesIndexRoute,
  AppOurVenuesIndexRoute: AppOurVenuesIndexRoute,
  AppTestingServicesIndexRoute: AppTestingServicesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
